# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Setup
title:            thanarino
tagline:          'dev boi'
description:      'woop woop'
baseurl:          //

author:
  name:           'Jonathan Ariño'
  url:            https://twitter.com/thanarino/

paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          0.1

github:
  repo:           https://github.com/thanarino/thanarino
